/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabcovid;

import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Maicon Esperafico, Matheus Oliveira
 */
public class TestCovid19 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TestCovid19() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        answer8 = new javax.swing.JComboBox<>();
        answer1 = new javax.swing.JComboBox<>();
        answer2 = new javax.swing.JComboBox<>();
        answer3 = new javax.swing.JComboBox<>();
        answer4 = new javax.swing.JComboBox<>();
        answer5 = new javax.swing.JComboBox<>();
        answer6 = new javax.swing.JComboBox<>();
        answer7 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnResult = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        probability = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        commentTitle = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TESTE COVID-19");
        setMaximumSize(new java.awt.Dimension(1010, 520));
        setMinimumSize(new java.awt.Dimension(1010, 520));
        setPreferredSize(new java.awt.Dimension(1010, 520));
        setResizable(false);
        setSize(new java.awt.Dimension(1010, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COVID-19");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1000, 40));

        answer8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO", "SIM" }));
        answer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer8ActionPerformed(evt);
            }
        });
        getContentPane().add(answer8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 190, -1));

        answer1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO", "SIM" }));
        answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1ActionPerformed(evt);
            }
        });
        getContentPane().add(answer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 190, -1));

        answer2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO", "SIM" }));
        answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2ActionPerformed(evt);
            }
        });
        getContentPane().add(answer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 190, -1));

        answer3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO", "SIM" }));
        answer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3ActionPerformed(evt);
            }
        });
        getContentPane().add(answer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 190, -1));

        answer4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO", "SIM" }));
        answer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer4ActionPerformed(evt);
            }
        });
        getContentPane().add(answer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 190, -1));

        answer5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO", "SIM" }));
        answer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer5ActionPerformed(evt);
            }
        });
        getContentPane().add(answer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 190, -1));

        answer6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO", "SIM" }));
        answer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer6ActionPerformed(evt);
            }
        });
        getContentPane().add(answer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 190, -1));

        answer7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO", "SIM" }));
        answer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer7ActionPerformed(evt);
            }
        });
        getContentPane().add(answer7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 190, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Resposta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 70, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Resposta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Resposta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Resposta:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Resposta:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("Resposta:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 70, 20));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("Resposta:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 70, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("Resposta:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 70, 20));

        jLabel10.setText("8. Você se sente cansado?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel11.setText("Para que o teste tenha uma melhor probabilidade, por favor responda as perguntas corretamente.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 560, -1));

        jLabel12.setText("2. Você está resfriado?");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel13.setText("3. Você está com tosse?");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel14.setText("4. Você stá com dor de garganta?");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel15.setText("5. Você tem dificuldade para respirar?");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel16.setText("6. Você está com febre?");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel17.setText("7. Você está com dor de cabeça?");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        btnResult.setText("Rodar Teste");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });
        getContentPane().add(btnResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 560, 30));

        jLabel18.setText("1. Você visitou recentemente um país afetado pelo Corona?");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(probability, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 70, 20));
        getContentPane().add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 470, 20));

        jLabel21.setText("Taxa de Probabilidade:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 130, 20));

        commentTitle.setText("Adendo:");
        getContentPane().add(commentTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 80, 20));

        jLabel23.setText("Informações:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, 20));

        commentBox.setEditable(false);
        commentBox.setColumns(20);
        commentBox.setRows(5);
        jScrollPane1.setViewportView(commentBox);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 560, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer8ActionPerformed

    private void answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1ActionPerformed

    private void answer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2ActionPerformed

    private void answer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer3ActionPerformed

    private void answer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer4ActionPerformed

    private void answer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer5ActionPerformed

    private void answer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer6ActionPerformed

    private void answer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer7ActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        double point = 0, sumanswers=0;

        if(answer1.getSelectedIndex() == 1){
            point += 2;
        }
        if(answer2.getSelectedIndex() == 1){
            point += 0.5;
        }
        if(answer3.getSelectedIndex() == 1){
            point += 0.5;
        }
        point += answer4.getSelectedIndex();
        point += answer5.getSelectedIndex();
        point += answer6.getSelectedIndex();
        point += answer7.getSelectedIndex();
        point += answer8.getSelectedIndex();

        sumanswers = (point / 8) * 100;
        if(sumanswers >= 100){
            sumanswers = 99;
        }
        if(sumanswers < 20){
            probability.setForeground(java.awt.Color.black);
            message.setForeground(java.awt.Color.black);
            message.setText("Muito pouco provável que você esteja infectado neste momento.");
            commentBox.setForeground(java.awt.Color.black);
            commentBox.setText("É muito pouco provável que você esteja infectado no momento.\nPara evitar riscos, lave as mãos regularmente e se possível fique em casa.");
        }
        else if(sumanswers < 40){
            probability.setForeground(java.awt.Color.black);
            message.setForeground(java.awt.Color.black);
            message.setText("Pouco provável que você esteja infectado neste momento.");
            commentBox.setForeground(java.awt.Color.black);
            commentBox.setText("Neste ponto, você tem menos probabilidade de estar infectado.\nPara evitar riscos, lave as mãos regularmente e se possível fique em casa.\nProcure atendimento médico em caso de emergência.");
        }
        else if(sumanswers < 60){
            probability.setForeground(java.awt.Color.blue);
            message.setForeground(java.awt.Color.blue);
            message.setText("Meio provável que você esteja infectado neste momento.");
            commentBox.setForeground(java.awt.Color.black);
            commentBox.setText("Você tem uma chance moderada de estar infectado.\nPor favor, use uma máscara e evite sair de casa.\nDe preferência, fique em casa em quarentena por 14 dias.\nProcure atendimento médico em caso de emergência.");
        }
        else if(sumanswers < 75){
            probability.setForeground(java.awt.Color.red);
            message.setForeground(java.awt.Color.red);
            message.setText("Mais provável que você esteja infectado neste momento.");
            commentBox.setForeground(java.awt.Color.red);
            commentBox.setText("É provável que você esteja infectado.\nFique em casa em quarentena por 14 dias.\nProcure atendimento médico em caso de emergência.");
        }
        else{
            probability.setForeground(java.awt.Color.red);
            message.setForeground(java.awt.Color.red);
            message.setText("Muito mais provável que você esteja infectado neste momento.");
            commentBox.setForeground(java.awt.Color.red);
            commentBox.setText("É muito provável que você esteja infectado.\nMantenha isolamento e utilize máscara para evitar a disseminação do vírus.\nProcure atentimento médico assim que possível.");
        }

        probability.setText(String.valueOf(String.format("%.0f%%", sumanswers)));
        
        new GenerateFile().run();
    }//GEN-LAST:event_btnResultActionPerformed

    private class GenerateFile extends Thread {

    	public void run() {
    		try {
    			FileWriter file = new FileWriter("Resultado.txt");
    			file.write("Taxa de probabilidade: " + probability.getText());
    			file.write("\n");
    			file.write("Informações: " + message.getText());
    			file.write("\n");
    			file.write(commentBox.getText());
    			file.close();
    			JOptionPane.showMessageDialog(null, "Arquivo resultado.txt criado!", "resultado.txt", 3);
                        
                        Desktop desktop = Desktop.getDesktop();
                        
                        File fileOpen = new File("Resultado.txt");
                        desktop.open(fileOpen);
    		
                } catch (IOException e) {
    			e.printStackTrace();
    		}
    	}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestCovid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestCovid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestCovid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestCovid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestCovid19().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> answer1;
    private javax.swing.JComboBox<String> answer2;
    private javax.swing.JComboBox<String> answer3;
    private javax.swing.JComboBox<String> answer4;
    private javax.swing.JComboBox<String> answer5;
    private javax.swing.JComboBox<String> answer6;
    private javax.swing.JComboBox<String> answer7;
    private javax.swing.JComboBox<String> answer8;
    private javax.swing.JButton btnResult;
    private javax.swing.JTextArea commentBox;
    private javax.swing.JLabel commentTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel probability;
    // End of variables declaration//GEN-END:variables
}
